using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using BillingSystem.Application.DTOs;
using BillingSystem.Application.Interfaces.Services;
using BillingSystem.Infrastructure.DbContext;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Microsoft.Extensions.Configuration;

namespace BillingSystem.Infrastructure.Services
{
    public class PdfService : IPdfService
    {
        private readonly BillingDbContext _context;
        private readonly IConfiguration _configuration;

        public PdfService(BillingDbContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        private static readonly Dictionary<string, Dictionary<string, string>> Labels = new()
        {
            ["en"] = new()
            {
                ["BillNo"] = "Bill No",
                ["PrintDate"] = "Print Date",
                ["GeneratedBy"] = "Generated By",
                ["GSTNo"] = "GST No",
                ["BankAc"] = "Bank A/C",
                ["PANNo"] = "PAN No",
                ["BillTo"] = "Bill To",
                ["Owner"] = "Owner",
                ["Phone"] = "Phone",
                ["Location"] = "Location",
                ["TaxRate"] = "Tax Rate",
                ["SrNo"] = "Sr No",
                ["Date"] = "Date",
                ["PartyName"] = "Party Name",
                ["Marko"] = "Marko",
                ["Quantity"] = "Quantity",
                ["Vigat"] = "Vigat / Remarks",
                ["Amount"] = "Amount",
                ["PageTotal"] = "Page Total",
                ["GrandTotal"] = "Grand Total",
                ["TaxCalculation"] = "Tax Calculation",
                ["FinalAmount"] = "Final Amount",
                ["AmountInWords"] = "Amount in Words",
                ["AuthorizedSignature"] = "Authorized Signature",
                ["ScanToPay"] = "Scan to Pay UPI",
                ["BrokerAgent"] = "Registered Broker Agent",
                ["Page"] = "Page",
                ["GrandTotalQuantity"] = "Grand Total Quantity",
                ["Calculation"] = "Calculation",
                ["FinalBillAmount"] = "Final Bill Amount",
                ["NotConfigured"] = "Not Configured",
                ["NotAvailable"] = "Not Available"
            },
            ["hi"] = new()
            {
                ["BillNo"] = "बिल नंबर",
                ["PrintDate"] = "प्रिंट तिथि",
                ["GeneratedBy"] = "द्वारा उत्पन्न",
                ["GSTNo"] = "जीएसटी नंबर",
                ["BankAc"] = "बैंक खाता",
                ["PANNo"] = "पैन नंबर",
                ["BillTo"] = "बिल प्राप्तकर्ता",
                ["Owner"] = "मालिक",
                ["Phone"] = "फोन",
                ["Location"] = "स्थान",
                ["TaxRate"] = "कर दर",
                ["SrNo"] = "क्र. सं.",
                ["Date"] = "तारीख",
                ["PartyName"] = "पक्ष का नाम",
                ["Marko"] = "मार्को",
                ["Quantity"] = "मात्रा",
                ["Vigat"] = "विवरण / रिमार्क्स",
                ["Amount"] = "रकम",
                ["PageTotal"] = "पृष्ठ कुल",
                ["GrandTotal"] = "कुल योग",
                ["TaxCalculation"] = "कर गणना",
                ["FinalAmount"] = "अंतिम राशि",
                ["AmountInWords"] = "शब्दों में राशि",
                ["AuthorizedSignature"] = "अधिकृत हस्ताक्षर",
                ["ScanToPay"] = "भुगतान के लिए स्कैन करें",
                ["BrokerAgent"] = "पंजीकृत ब्रोकर एजेंट",
                ["Page"] = "पृष्ठ",
                ["GrandTotalQuantity"] = "कुल मात्रा",
                ["Calculation"] = "गणना",
                ["FinalBillAmount"] = "अंतिम बिल राशि",
                ["NotConfigured"] = "कॉन्फ़िगर नहीं किया गया",
                ["NotAvailable"] = "अनुपलब्ध"
            },
            ["gu"] = new()
            {
                ["BillNo"] = "બિલ નંબર",
                ["PrintDate"] = "પ્રિન્ટ તારીખ",
                ["GeneratedBy"] = "દ્વારા જનરેટ",
                ["GSTNo"] = "જીએસટી નંબર",
                ["BankAc"] = "બેંક ખાતું",
                ["PANNo"] = "પાન નંબર",
                ["BillTo"] = "બિલ મેળવનાર",
                ["Owner"] = "માલિક",
                ["Phone"] = "ફોન",
                ["Location"] = "સ્થળ",
                ["TaxRate"] = "ટેક્સ દર",
                ["SrNo"] = "ક્રમ",
                ["Date"] = "તારીખ",
                ["PartyName"] = "પક્ષનું નામ",
                ["Marko"] = "માર્કો",
                ["Quantity"] = "જથ્થો",
                ["Vigat"] = "વિગત / રીમાર્કસ",
                ["Amount"] = "રકમ",
                ["PageTotal"] = "પાનાનો સરવાળો",
                ["GrandTotal"] = "કુલ સરવાળો",
                ["TaxCalculation"] = "ટેક્સ ગણતરી",
                ["FinalAmount"] = "અંતિમ રકમ",
                ["AmountInWords"] = "શબ્દોમાં રકમ",
                ["AuthorizedSignature"] = "સહી",
                ["ScanToPay"] = "ચુકવણી માટે સ્કેન કરો",
                ["BrokerAgent"] = "રજીસ્ટર્ડ બ્રોકર એજન્ટ",
                ["Page"] = "પાનું",
                ["GrandTotalQuantity"] = "કુલ જથ્થો",
                ["Calculation"] = "ગણતરી",
                ["FinalBillAmount"] = "અંતિમ બિલ રકમ",
                ["NotConfigured"] = "રૂપરેખાંકિત નથી",
                ["NotAvailable"] = "ઉપલબ્ધ નથી"
            }
        };

        private string GetLabel(string key, string lang)
        {
            var cleanLang = lang.ToLower() == "guj" ? "gu" : lang.ToLower();
            if (!Labels.ContainsKey(cleanLang)) cleanLang = "en";
            return Labels[cleanLang].ContainsKey(key) ? Labels[cleanLang][key] : key;
        }

        public async Task<byte[]> GenerateLedgerPdfAsync(int id, string type, string lang, int userId)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserNo == userId);
            var config = await _context.BillConfigurations.FirstOrDefaultAsync(c => c.UserNo == userId);

            var dto = new BillPdfDto
            {
                BillNumber = $"BIL-{DateTime.UtcNow:yyyyMMdd}-{new Random().Next(1000, 9999)}",
                PrintDateString = DateTime.Now.ToString("dd-MM-yyyy hh:mm tt"),
                GeneratedBy = user != null ? $"{user.vfirstname} {user.vlastname}".Trim() : "Broker System",
                BrokerName = user != null ? $"{user.vfirstname} {user.vlastname}".Trim() : "Broker System",
                GSTNumber = config?.GSTNumber ?? "---",
                BankAccountNumber = config?.BankAccountNumber ?? "---",
                PANNumber = config?.PANNumber ?? "---",
                LeftImagePath = config?.LeftImagePath,
                RightImagePath = config?.RightImagePath,
                QRCodeImagePath = config?.QRCodeImagePath
            };

            var cleanLang = lang.ToLower();
            if (cleanLang == "guj") cleanLang = "gu";

            if (type.ToLower() == "mill")
            {
                var mill = await _context.UserMills
                    .Include(m => m.UserState)
                    .Include(m => m.UserDistrict)
                    .FirstOrDefaultAsync(m => m.MillNo == id);

                if (mill != null)
                {
                    dto.PartnerName = cleanLang == "gu" ? (mill.MillName_guj ?? mill.MillName_en ?? "") :
                                     cleanLang == "hi" ? (mill.MillName_hi ?? mill.MillName_en ?? "") : (mill.MillName_en ?? "");
                    
                    dto.PartnerOwnerName = cleanLang == "gu" ? (mill.OwnerName_guj ?? mill.OwnerName_en ?? "") :
                                          cleanLang == "hi" ? (mill.OwnerName_hi ?? mill.OwnerName_en ?? "") : (mill.OwnerName_en ?? "");

                    dto.PartnerPhone = mill.OwnerPhoneNo ?? "";
                    
                    var stateName = cleanLang == "gu" ? (mill.UserState?.StateName_guj ?? mill.UserState?.StateName_en ?? "") :
                                    cleanLang == "hi" ? (mill.UserState?.StateName_hi ?? mill.UserState?.StateName_en ?? "") : (mill.UserState?.StateName_en ?? "");

                    var districtName = cleanLang == "gu" ? (mill.UserDistrict?.DistrictName_guj ?? mill.UserDistrict?.DistrictName_en ?? "") :
                                        cleanLang == "hi" ? (mill.UserDistrict?.DistrictName_hi ?? mill.UserDistrict?.DistrictName_en ?? "") : (mill.UserDistrict?.DistrictName_en ?? "");

                    var locationText = cleanLang == "gu" ? (mill.Location_guj ?? mill.Location_en ?? "") :
                                       cleanLang == "hi" ? (mill.Location_hi ?? mill.Location_en ?? "") : (mill.Location_en ?? "");

                    dto.PartnerLocation = $"{locationText}, {districtName}, {stateName}".Trim(',', ' ', '/');
                    dto.TaxRate = mill.MillTaxInfo ?? 0;
                }

                var txs = await _context.LedgerTransactions
                    .Include(t => t.UserDukan)
                    .Include(t => t.UserMarko)
                    .Where(t => t.MillNo == id && t.IsActive)
                    .OrderBy(t => t.TransactionDate)
                    .ToListAsync();

                int srNo = 1;
                foreach (var tx in txs)
                {
                    var dukanName = cleanLang == "gu" ? (tx.UserDukan?.DukanName_guj ?? tx.UserDukan?.DukanName_en ?? "") :
                                    cleanLang == "hi" ? (tx.UserDukan?.DukanName_hi ?? tx.UserDukan?.DukanName_en ?? "") : (tx.UserDukan?.DukanName_en ?? "");

                    var markoName = cleanLang == "gu" ? (tx.UserMarko?.MarkoName_guj ?? tx.UserMarko?.MarkoName_en ?? "") :
                                    cleanLang == "hi" ? (tx.UserMarko?.MarkoName_hi ?? tx.UserMarko?.MarkoName_en ?? "") : (tx.UserMarko?.MarkoName_en ?? "");

                    var vigatText = cleanLang == "gu" ? (tx.Vigat_guj ?? tx.Vigat_en ?? "") :
                                    cleanLang == "hi" ? (tx.Vigat_hi ?? tx.Vigat_en ?? "") : (tx.Vigat_en ?? "");

                    dto.Entries.Add(new BillPdfEntryDto
                    {
                        SrNo = srNo++,
                        DateString = tx.TransactionDate.ToString("dd-MM-yyyy"),
                        PartyOrMillName = dukanName,
                        MarkoName = markoName,
                        Quantity = tx.Quantity,
                        Vigat = vigatText
                    });
                }
            }
            else if (type.ToLower() == "dukan")
            {
                var dukan = await _context.UserDukans
                    .Include(d => d.UserState)
                    .Include(d => d.UserDistrict)
                    .FirstOrDefaultAsync(d => d.DukanNo == id);

                if (dukan != null)
                {
                    dto.PartnerName = cleanLang == "gu" ? (dukan.DukanName_guj ?? dukan.DukanName_en ?? "") :
                                     cleanLang == "hi" ? (dukan.DukanName_hi ?? dukan.DukanName_en ?? "") : (dukan.DukanName_en ?? "");
                    
                    dto.PartnerOwnerName = cleanLang == "gu" ? (dukan.OwnerName_guj ?? dukan.OwnerName_en ?? "") :
                                          cleanLang == "hi" ? (dukan.OwnerName_hi ?? dukan.OwnerName_en ?? "") : (dukan.OwnerName_en ?? "");

                    dto.PartnerPhone = dukan.OwnerPhoneNo ?? "";
                    
                    var stateName = cleanLang == "gu" ? (dukan.UserState?.StateName_guj ?? dukan.UserState?.StateName_en ?? "") :
                                    cleanLang == "hi" ? (dukan.UserState?.StateName_hi ?? dukan.UserState?.StateName_en ?? "") : (dukan.UserState?.StateName_en ?? "");

                    var districtName = cleanLang == "gu" ? (dukan.UserDistrict?.DistrictName_guj ?? dukan.UserDistrict?.DistrictName_en ?? "") :
                                        cleanLang == "hi" ? (dukan.UserDistrict?.DistrictName_hi ?? dukan.UserDistrict?.DistrictName_en ?? "") : (dukan.UserDistrict?.DistrictName_en ?? "");

                    var locationText = cleanLang == "gu" ? (dukan.Location_guj ?? dukan.Location_en ?? "") :
                                       cleanLang == "hi" ? (dukan.Location_hi ?? dukan.Location_en ?? "") : (dukan.Location_en ?? "");

                    dto.PartnerLocation = $"{locationText}, {districtName}, {stateName}".Trim(',', ' ', '/');
                    dto.TaxRate = dukan.DukanTaxInfo ?? 0;
                }

                var txs = await _context.LedgerTransactions
                    .Include(t => t.UserMill)
                    .Include(t => t.UserMarko)
                    .Where(t => t.DukanNo == id && t.IsActive)
                    .OrderBy(t => t.TransactionDate)
                    .ToListAsync();

                int srNo = 1;
                foreach (var tx in txs)
                {
                    var millName = cleanLang == "gu" ? (tx.UserMill?.MillName_guj ?? tx.UserMill?.MillName_en ?? "") :
                                   cleanLang == "hi" ? (tx.UserMill?.MillName_hi ?? tx.UserMill?.MillName_en ?? "") : (tx.UserMill?.MillName_en ?? "");

                    var markoName = cleanLang == "gu" ? (tx.UserMarko?.MarkoName_guj ?? tx.UserMarko?.MarkoName_en ?? "") :
                                    cleanLang == "hi" ? (tx.UserMarko?.MarkoName_hi ?? tx.UserMarko?.MarkoName_en ?? "") : (tx.UserMarko?.MarkoName_en ?? "");

                    var vigatText = cleanLang == "gu" ? (tx.Vigat_guj ?? tx.Vigat_en ?? "") :
                                    cleanLang == "hi" ? (tx.Vigat_hi ?? tx.Vigat_en ?? "") : (tx.Vigat_en ?? "");

                    dto.Entries.Add(new BillPdfEntryDto
                    {
                        SrNo = srNo++,
                        DateString = tx.TransactionDate.ToString("dd-MM-yyyy"),
                        PartyOrMillName = millName,
                        MarkoName = markoName,
                        Quantity = tx.Quantity,
                        Vigat = vigatText
                    });
                }
            }

            var pdfStream = new MemoryStream();

            var leftImgBytes = LoadImageBytes(dto.LeftImagePath);
            var rightImgBytes = LoadImageBytes(dto.RightImagePath);
            var qrImgBytes = LoadImageBytes(dto.QRCodeImagePath);

            // Using standard A4 format and Nirmala UI font to support Indic translations
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(0.5f, Unit.Inch);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Nirmala UI").FontColor(Colors.Grey.Darken3));

                    // Header
                    page.Header().Column(col =>
                    {
                        col.Item().Row(row =>
                        {
                            // Left image
                            if (leftImgBytes != null)
                            {
                                row.ConstantItem(50).Height(50).Image(leftImgBytes).FitArea();
                            }
                            else
                            {
                                row.ConstantItem(50).Height(50).AlignMiddle().AlignCenter().Text("🔱").FontSize(24);
                            }

                            // Center metadata block
                            row.RelativeItem().AlignCenter().Column(headerCol =>
                            {
                                headerCol.Item().Text(dto.BrokerName).FontSize(14).Bold().FontColor(Colors.Blue.Darken3).AlignCenter();
                                headerCol.Item().Text(GetLabel("BrokerAgent", lang)).FontSize(8).Italic().FontColor(Colors.Grey.Medium).AlignCenter();
                                
                                headerCol.Item().PaddingTop(4).Row(metaRow =>
                                {
                                    metaRow.RelativeItem().Text($"{GetLabel("BillNo", lang)}: {dto.BillNumber}").FontSize(8).AlignCenter();
                                    metaRow.RelativeItem().Text($"{GetLabel("PrintDate", lang)}: {dto.PrintDateString}").FontSize(8).AlignCenter();
                                });
                                headerCol.Item().Text($"{GetLabel("GeneratedBy", lang)}: {dto.GeneratedBy}").FontSize(8).AlignCenter();
                            });

                            // Right image
                            if (rightImgBytes != null)
                            {
                                row.ConstantItem(50).Height(50).Image(rightImgBytes).FitArea();
                            }
                            else
                            {
                                row.ConstantItem(50).Height(50).AlignMiddle().AlignCenter().Text("🔱").FontSize(24);
                            }
                        });

                        col.Item().PaddingVertical(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);

                        // Client vs Broker Credentials block
                        col.Item().Row(credRow =>
                        {
                            credRow.RelativeItem().Column(brokerCol =>
                            {
                                brokerCol.Item().Text($"{GetLabel("GSTNo", lang)}: {dto.GSTNumber}").Bold();
                                brokerCol.Item().Text($"{GetLabel("BankAc", lang)}: {dto.BankAccountNumber}");
                                brokerCol.Item().Text($"{GetLabel("PANNo", lang)}: {dto.PANNumber}");
                            });

                            credRow.ConstantItem(20);

                            credRow.RelativeItem().AlignRight().Column(clientCol =>
                            {
                                clientCol.Item().Text($"{GetLabel("BillTo", lang)}: {dto.PartnerName}").Bold();
                                clientCol.Item().Text($"{GetLabel("Owner", lang)}: {dto.PartnerOwnerName}");
                                clientCol.Item().Text($"{GetLabel("Phone", lang)}: {dto.PartnerPhone}");
                                clientCol.Item().Text($"{GetLabel("Location", lang)}: {dto.PartnerLocation}");
                                string headerTaxRateStr = dto.TaxRate > 0 ? $"{dto.TaxRate:0.00}" : GetLabel("NotConfigured", lang);
                                clientCol.Item().Text($"{GetLabel("TaxRate", lang)}: {headerTaxRateStr}");
                            });
                        });

                        col.Item().PaddingTop(8).LineHorizontal(1.5f).LineColor(Colors.Grey.Darken2);
                    });

                    // Content
                    page.Content().PaddingVertical(10).Column(contentCol =>
                    {
                        var groups = dto.Entries.Select((x, i) => new { Index = i, Value = x })
                                                .GroupBy(x => x.Index / 25)
                                                .Select(g => g.Select(x => x.Value).ToList())
                                                .ToList();

                        if (groups.Count == 0)
                        {
                            contentCol.Item().AlignCenter().Padding(20).Text("No transactions recorded.").Italic().FontColor(Colors.Grey.Medium);
                            return;
                        }

                        for (int pageIndex = 0; pageIndex < groups.Count; pageIndex++)
                        {
                            var group = groups[pageIndex];
                            bool isLastPage = (pageIndex == groups.Count - 1);
                            decimal pageQty = group.Sum(e => e.Quantity);

                            contentCol.Item().Table(table =>
                            {
                                // Columns: Sr No, Date, Party Name, Marko, Qty, Vigat
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.ConstantColumn(30);  // Sr No
                                    columns.ConstantColumn(70);  // Date
                                    columns.RelativeColumn(2.5f); // Party Name
                                    columns.RelativeColumn(1.2f); // Marko
                                    columns.ConstantColumn(70);  // Qty (Right align)
                                    columns.RelativeColumn(3f);  // Vigat
                                });

                                // Header row
                                table.Header(header =>
                                {
                                    header.Cell().Element(CellStyle).Text(GetLabel("SrNo", lang)).Bold();
                                    header.Cell().Element(CellStyle).Text(GetLabel("Date", lang)).Bold();
                                    header.Cell().Element(CellStyle).Text(GetLabel("PartyName", lang)).Bold();
                                    header.Cell().Element(CellStyle).Text(GetLabel("Marko", lang)).Bold();
                                    header.Cell().Element(CellRightStyle).Text(GetLabel("Quantity", lang)).Bold();
                                    header.Cell().Element(CellStyle).Text(GetLabel("Vigat", lang)).Bold();

                                    static IContainer CellStyle(IContainer container) => container.BorderBottom(1).BorderColor(Colors.Grey.Darken1).PaddingVertical(4);
                                    static IContainer CellRightStyle(IContainer container) => container.BorderBottom(1).BorderColor(Colors.Grey.Darken1).PaddingVertical(4).AlignRight();
                                });

                                // Rows
                                foreach (var entry in group)
                                {
                                    table.Cell().Element(CellStyle).Text(entry.SrNo.ToString());
                                    table.Cell().Element(CellStyle).Text(entry.DateString);
                                    table.Cell().Element(CellStyle).Text(entry.PartyOrMillName).Bold();
                                    table.Cell().Element(CellStyle).Text(entry.MarkoName);
                                    table.Cell().Element(CellRightStyle).Text(entry.Quantity.ToString("0.00"));
                                    table.Cell().Element(CellStyle).Text(entry.Vigat);

                                    static IContainer CellStyle(IContainer container) => container.BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).PaddingVertical(4);
                                    static IContainer CellRightStyle(IContainer container) => container.BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).PaddingVertical(4).AlignRight();
                                }

                                // Page Total Footer Row
                                table.Footer(footer =>
                                {
                                    footer.Cell().Element(CellStyle); // Sr No
                                    footer.Cell().Element(CellStyle); // Date
                                    footer.Cell().Element(CellStyle); // Party Name
                                    footer.Cell().Element(CellStyle).AlignRight().Text($"{GetLabel("PageTotal", lang)}:").Bold(); // Marko
                                    footer.Cell().Element(CellRightStyle).Text(pageQty.ToString("0.00")).Bold(); // Qty
                                    footer.Cell().Element(CellStyle); // Vigat

                                    static IContainer CellStyle(IContainer container) => container.BorderTop(1).BorderColor(Colors.Grey.Darken1).PaddingVertical(6);
                                    static IContainer CellRightStyle(IContainer container) => container.BorderTop(1).BorderColor(Colors.Grey.Darken1).PaddingVertical(6).AlignRight();
                                });
                            });

                            if (isLastPage)
                            {
                                // Summary Section & Last Page Total Summary block
                                decimal grandQty = dto.Entries.Sum(e => e.Quantity);
                                bool isTaxConfigured = dto.TaxRate > 0;
                                string taxRateStr = isTaxConfigured ? $"{dto.TaxRate:0.00}" : GetLabel("NotConfigured", lang);
                                string finalAmountStr = isTaxConfigured ? $"{(grandQty * dto.TaxRate):0.00}" : GetLabel("NotAvailable", lang);
                                string calculationStr = isTaxConfigured ? $"{grandQty:0.00} × {dto.TaxRate:0.00} = {(grandQty * dto.TaxRate):0.00}" : $"{grandQty:0.00} × {GetLabel("NotConfigured", lang)}";

                                contentCol.Item().PaddingTop(15).Row(sumRow =>
                                {
                                    sumRow.RelativeItem(2.5f); // Empty spacer
                                    
                                    sumRow.RelativeItem(2.5f).Border(0.5f).BorderColor(Colors.Grey.Medium).Column(colSummary =>
                                    {
                                        // Grand Total Quantity
                                        colSummary.Item().Row(r =>
                                        {
                                            r.RelativeItem().Padding(4).Text(GetLabel("GrandTotalQuantity", lang)).Bold();
                                            r.RelativeItem().Padding(4).AlignRight().Text(grandQty.ToString("0.00")).Bold();
                                        });

                                        colSummary.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Medium);

                                        // Tax Rate
                                        colSummary.Item().Row(r =>
                                        {
                                            r.RelativeItem().Padding(4).Text(GetLabel("TaxRate", lang));
                                            r.RelativeItem().Padding(4).AlignRight().Text(taxRateStr);
                                        });

                                        colSummary.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Medium);

                                        // Calculation
                                        colSummary.Item().Row(r =>
                                        {
                                            r.RelativeItem().Padding(4).Text(GetLabel("Calculation", lang));
                                            r.RelativeItem().Padding(4).AlignRight().Text(calculationStr);
                                        });

                                        colSummary.Item().LineHorizontal(1).LineColor(Colors.Grey.Darken2);

                                        // Final Bill Amount
                                        colSummary.Item().Background(Colors.Grey.Lighten3).Row(r =>
                                        {
                                            r.RelativeItem().Padding(4).Text(GetLabel("FinalBillAmount", lang)).Bold().FontColor(Colors.Blue.Darken3);
                                            r.RelativeItem().Padding(4).AlignRight().Text(finalAmountStr).Bold().FontColor(Colors.Blue.Darken3);
                                        });
                                    });
                                });

                                // Signature area & Payment QR Code
                                contentCol.Item().ShowEntire().PaddingTop(30).Row(footerRow =>
                                {
                                    // Scan to Pay QR Block on left
                                    if (qrImgBytes != null)
                                    {
                                        footerRow.ConstantItem(140).Column(qrCol =>
                                        {
                                            qrCol.Item().AlignCenter().Text(GetLabel("ScanToPay", lang)).FontSize(7).Bold().FontColor(Colors.Grey.Darken1);
                                            qrCol.Item().PaddingTop(4).Height(80).Width(80).AlignCenter().Image(qrImgBytes).FitArea();
                                        });
                                    }
                                    else
                                    {
                                        footerRow.ConstantItem(140).Column(qrCol =>
                                        {
                                            qrCol.Item().AlignCenter().Text(GetLabel("ScanToPay", lang)).FontSize(7).Bold().FontColor(Colors.Grey.Darken1);
                                            qrCol.Item().PaddingTop(4).Height(80).Width(80).AlignCenter().Border(1).BorderColor(Colors.Grey.Lighten1).AlignMiddle().Text("QR Code").FontSize(8).FontColor(Colors.Grey.Medium);
                                        });
                                    }

                                    footerRow.RelativeItem(); // Spacer

                                    // Signature Line on right
                                    footerRow.ConstantItem(150).Column(sigCol =>
                                        {
                                            sigCol.Item().PaddingTop(50).LineHorizontal(1).LineColor(Colors.Grey.Darken1);
                                            sigCol.Item().PaddingTop(4).AlignCenter().Text(GetLabel("AuthorizedSignature", lang)).FontSize(8).Bold();
                                        });
                                });
                            }
                            else
                            {
                                contentCol.Item().PageBreak();
                            }
                        }
                    });

                    // Footer - Dynamic Page Count
                    page.Footer().AlignRight().Text(text =>
                    {
                        text.Span($"{GetLabel("Page", lang)} ");
                        text.CurrentPageNumber();
                        text.Span(" / ");
                        text.TotalPages();
                    });
                });
            });

            document.GeneratePdf(pdfStream);
            return pdfStream.ToArray();
        }

        private byte[]? LoadImageBytes(string? relativePath)
        {
            if (string.IsNullOrEmpty(relativePath)) return null;
            try
            {
                var cleanPath = relativePath.Replace('/', Path.DirectorySeparatorChar).TrimStart(Path.DirectorySeparatorChar);
                const string uploadsPrefix = "uploads";
                if (cleanPath.StartsWith(uploadsPrefix, StringComparison.OrdinalIgnoreCase))
                {
                    cleanPath = cleanPath.Substring(uploadsPrefix.Length).TrimStart(Path.DirectorySeparatorChar);
                }

                var uploadRoot = _configuration["StorageSettings:UploadRoot"] ?? "wwwroot/uploads";
                string fullPath;
                if (Path.IsPathRooted(uploadRoot))
                {
                    fullPath = Path.Combine(uploadRoot, cleanPath);
                }
                else
                {
                    fullPath = Path.Combine(Directory.GetCurrentDirectory(), uploadRoot, cleanPath);
                }

                if (File.Exists(fullPath))
                {
                    return File.ReadAllBytes(fullPath);
                }
            }
            catch
            {
                // Ignore
            }
            return null;
        }
    }
}
